README.md
src/function/src/aws/lambda.rs

doc: add comments to test CLA

---

src/test/src/lib.rs

feat!: random generate record batches

---

src/runtime/Cargo.toml
src/runtime/src/context.rs
src/runtime/src/encoding.rs
src/runtime/src/lib.rs
src/runtime/src/payload.rs

test: serialization

---

src/runtime/src/encoding.rs
src/runtime/src/payload.rs

fix: encoding::none handler

---

src/function/src/aws/lambda.rs
src/runtime/src/payload.rs

feat!:  call next functions in parallel

---

src/runtime/Cargo.toml
src/runtime/src/arena/bitmap.rs
src/runtime/src/arena/mod.rs
src/runtime/src/datasource/mod.rs
src/runtime/src/lib.rs

feat!: global data structure to reassemble windows

---

src/function/Cargo.toml
src/function/src/aws/lambda.rs
src/runtime/src/arena/mod.rs
src/runtime/src/prelude.rs

feat!: payload_handler in the generic lambda

---

src/function/src/aws/lambda.rs
src/runtime/src/context.rs

feat!: conditional processing for different stages of dataflow

---

nexmark/src/queries/q0.sql
nexmark/src/queries/q1.sql
nexmark/src/queries/q2.sql
nexmark/src/queries/q3.sql
nexmark/src/queries/q4.sql
nexmark/src/queries/q5.sql
nexmark/src/queries/q6.sql
nexmark/src/queries/q7.sql
nexmark/src/queries/q8.sql

sql: 8 netmark queries

---

nexmark/src/config.rs
nexmark/src/event.rs
nexmark/src/generator.rs
src/function/src/aws/lambda.rs
src/runtime/Cargo.toml
src/runtime/src/datasource/mod.rs
src/runtime/src/datasource/nexmark.rs
src/runtime/src/query/stream.rs

feat!: nexmark benchmark data source

---

src/runtime/src/datasource/nexmark/event.rs
src/runtime/src/datasource/nexmark/generator.rs
src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/datasource/nexmark/queries/q0.rs

nextmark: local execution - query 0

---

src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q1.rs

nextmark: local execution - query 1

---

src/runtime/src/datasource/nexmark/config.rs
src/runtime/src/datasource/nexmark/event.rs
src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q1.rs
src/runtime/src/datasource/nexmark/queries/q2.rs
src/runtime/src/datasource/nexmark/queries/q3.rs

nextmark: local execution - query 3

---

src/runtime/src/datasource/nexmark/event.rs
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q1.rs
src/runtime/src/datasource/nexmark/queries/q4.rs

nextmark: local execution - query 4

---

src/runtime/src/datasource/nexmark/event.rs

fix: match schema name

---

src/driver/src/deploy/mod.rs
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q5.rs
src/runtime/src/datasource/nexmark/queries/q5.sql
src/runtime/src/query/stream.rs

nextmark: local execution - query 5

---

src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q8.rs

nextmark: local execution - query 8

---

src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q7.rs

nexmark: local execution - query 7

---

src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q6.rs

nexmark benchmark: local execution - query 6

---

src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q2.rs

nexmark benchmark: local execution - query 2

---

src/runtime/src/datasource/nexmark/queries/q13.sql

nextmark: sql query 13

---

src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q9.rs
src/runtime/src/datasource/nexmark/queries/q9.sql

nexmark benchmark: local execution - query 9

---

src/runtime/src/datasource/nexmark/mod.rs
src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/datasource/nexmark/queries/q0.rs
src/runtime/src/datasource/nexmark/queries/q1.rs
src/runtime/src/datasource/nexmark/queries/q2.rs
src/runtime/src/datasource/nexmark/queries/q3.rs
src/runtime/src/datasource/nexmark/queries/q4.rs
src/runtime/src/datasource/nexmark/queries/q5.rs
src/runtime/src/datasource/nexmark/queries/q6.rs
src/runtime/src/datasource/nexmark/queries/q7.rs
src/runtime/src/datasource/nexmark/queries/q8.rs
src/runtime/src/datasource/nexmark/queries/q9.rs
src/runtime/src/prelude.rs
src/test/Cargo.toml
src/test/src/umd_runtime.rs

test: umd lambda runtime

---

.codecov.yml
src/driver/src/funcgen/function.rs
src/function/Cargo.toml
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/lambda.rs
src/runtime/src/context.rs
src/runtime/src/executor/mod.rs

feat!: generic nexmark lambda

---

README.md

docs: nexmark

---

.codecov.yml
README.md
src/bin/cli/Cargo.toml
src/bin/cli/src/repl.rs
src/bin/cli/src/squirtle.txt
src/function/Cargo.toml

feat!: function code to s3

---

benchmarks/Cargo.toml
benchmarks/nexmark/main.rs
src/bin/cli/src/repl.rs
src/driver/src/deploy/lambda.rs
src/function/Cargo.toml
src/function/src/aws/hello.rs

fix: workflow of entire system

---

benchmarks/nexmark/main.rs

feat!: async io programming

---

src/function/src/aws/nexmark/lambda.rs

feat!: return epoch number and data source id

---

benchmarks/Cargo.toml
benchmarks/nexmark/main.rs

fix: async nested loop

---

.github/workflows/rust.yml
benchmarks/Cargo.toml
benchmarks/nexmark/main.rs
src/driver/Cargo.toml
src/driver/src/funcgen/dag.rs
src/driver/src/funcgen/function.rs
src/function/Cargo.toml
src/legacy/datasource/Cargo.toml
src/legacy/examples/Cargo.toml
src/legacy/logical_plan/Cargo.toml
src/legacy/physical_plan/Cargo.toml
src/runtime/Cargo.toml
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/queries/q0.rs
src/runtime/src/datasource/nexmark/queries/q1.rs
src/runtime/src/datasource/nexmark/queries/q2.rs
src/runtime/src/datasource/nexmark/queries/q3.rs
src/runtime/src/datasource/nexmark/queries/q4.rs
src/runtime/src/datasource/nexmark/queries/q5.rs
src/runtime/src/datasource/nexmark/queries/q6.rs
src/runtime/src/datasource/nexmark/queries/q7.rs
src/runtime/src/datasource/nexmark/queries/q8.rs
src/runtime/src/datasource/nexmark/queries/q9.rs
src/runtime/src/encoding.rs
src/runtime/src/executor/mod.rs
src/runtime/src/payload.rs
src/test/Cargo.toml
src/test/data/plan/aggregate.json
src/test/data/plan/join.json
src/test/src/lib.rs

upgrade: new arrow-rs and arrow-datafusion

---

.codecov.yml
benchmarks/nexmark/main.rs
src/function/src/aws/nexmark/lambda.rs
src/runtime/src/context.rs

cloud: q3 and q4

---

benchmarks/nexmark/main.rs
src/driver/src/funcgen/function.rs
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/lambda.rs
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/queries/q5.rs
src/runtime/src/executor/mod.rs

feat: debuggable lambda functions

---

benchmarks/nexmark/main.rs

feat!: streaming window to cloud

---

.github/workflows/rust.yml
benchmarks/Cargo.toml
src/bin/cli/Cargo.toml
src/driver/Cargo.toml
src/driver/src/funcgen/dag.rs
src/function/Cargo.toml
src/legacy/ops/Cargo.toml
src/legacy/physical_plan/Cargo.toml
src/runtime/Cargo.toml
src/test/Cargo.toml

rusoto: a major version bump

---

.pre-commit-config.yaml
Cargo.toml
src/driver/Cargo.toml
src/driver/src/deploy/lambda.rs
src/driver/src/funcgen/dag.rs
src/function/src/aws/lambda.rs
src/runtime/Cargo.toml
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/queries/q6.rs
src/runtime/src/encoding.rs
src/runtime/src/executor/mod.rs
src/runtime/src/payload.rs
src/test/Cargo.toml

fix: test error after bump deps version

---

src/driver/src/funcgen/function.rs

docs: improve function.rs codestyle and comments

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ISSUE_TEMPLATE/bug_report.md
.github/workflows/ISSUE_TEMPLATE/feature_request.md
.github/workflows/ISSUE_TEMPLATE/question.md

github: add more guidelines and AGPL license for this project.

---

src/driver/src/funcgen/function.rs
src/runtime/src/arena/bitmap.rs
src/runtime/src/arena/mod.rs
src/runtime/src/payload.rs

docs: add comments for payload and bitmap

---

.pre-commit-config.yaml
README.md
bench/Cargo.toml
src/bin/cli/src/flock.txt
src/driver/Cargo.toml
src/function/Cargo.toml
src/runtime/Cargo.toml
src/test/Cargo.toml

Closes #.
All prior dependent projects were mingled in the DSLAM-UMD, making management difficult. I formed a new organization to oversee Flock-related repositories.

repo: move to a new organization for better management

---

docs/main.scrbl

docs: adjust picture

---

.github/workflows/rust.yml
docs/main.scrbl

ci: paths changes filter to skip ci

---

docs/benchmarks.scrbl
docs/benchmarks/ec2.scrbl
docs/benchmarks/flink.scrbl
docs/main.scrbl

docs: flink intro

---

docs/benchmarks/nexmark.scrbl

docs: flink nexmark

---

bench/Cargo.toml
bench/nexmark/main.rs
fn_bench.sh

feat: add query timestamp

---

bench/Cargo.toml
bench/nexmark/main.rs
src/driver/src/deploy/lambda.rs
src/driver/src/funcgen/function.rs
src/function/Cargo.toml
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/lambda.rs
src/runtime/src/arena/mod.rs
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/queries/q5.rs
src/runtime/src/executor/mod.rs
src/runtime/src/payload.rs

feat: add nexmark generator to the first function

---

src/driver/Cargo.toml
src/function/Cargo.toml
src/playground/Cargo.toml
src/runtime/Cargo.toml
src/test/Cargo.toml
src/test/data/example-kafka-event.json

feat: bump aws_lambda_events version to 0.5

---

bench/nexmark/main.rs
bench/nexmark/query/q0.sql
bench/nexmark/query/q1.sql
bench/nexmark/query/q2.sql
bench/nexmark/query/q3.sql
bench/nexmark/query/q4.sql
bench/nexmark/query/q5.sql
bench/nexmark/query/q6.sql
bench/nexmark/query/q7.sql
bench/nexmark/query/q8.sql
bench/nexmark/query/q9.sql
src/driver/src/funcgen/dag.rs
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/event.rs

feat: refine bench code and add feed_data_sources

---

src/function/Cargo.toml
src/function/src/aws/nexmark/lambda.rs
src/runtime/src/payload.rs

feat!: hopping window on cloud

---

src/function/src/aws/nexmark/lambda.rs

fix: hopping window for nexmark q5

---

nexmark.sh

Closes #.
Flock can easily support millions of events per second now.

fix: help() in nexmark.sh

---

nexmark.sh

bench: set the upper limit to control cloud budget

---

nexmark.sh
scripts/rainbow.sh

bench: refine the output

---

.pre-commit-config.yaml
bench/nexmark/main.rs
bench/nexmark/query/q6.sql
nexmark.sh
src/runtime/Cargo.toml
src/runtime/src/datasource/nexmark/event.rs
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q3.rs
src/runtime/src/datasource/nexmark/queries/q4.rs
src/runtime/src/datasource/nexmark/queries/q5.rs
src/runtime/src/datasource/nexmark/queries/q6_v2.rs
src/runtime/src/datasource/nexmark/queries/q7.rs
src/runtime/src/datasource/nexmark/queries/q8.rs

feat: simplify nexmark query 6 using one sql stmt

---

src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q6_v3.rs

added q6_v3

---

.github/workflows/rust.yml
bench/Cargo.toml
bench/nexmark/main.rs
src/bin/cli/Cargo.toml
src/driver/Cargo.toml
src/function/Cargo.toml
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/executor.rs
src/function/src/aws/nexmark/main.rs
src/playground/Cargo.toml
src/runtime/Cargo.toml
src/runtime/src/config/flock.toml
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/queries/q6_v3.rs
src/test/Cargo.toml

feat!: add s3 as a fallback place for query  plan

---

bench/nexmark/query/q6.sql

fix: add q6 v3 as a default query in benchmark

---

src/function/src/aws/nexmark/main.rs
src/function/src/aws/nexmark/window.rs

Closes #.
invoke lambda function is async, there is no need to use async tokio task

fix: remove tokio async task

---

bench/nexmark/main.rs
nexmark.sh
src/driver/src/deploy/lambda.rs
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/executor.rs
src/function/src/aws/nexmark/main.rs
src/function/src/aws/nexmark/utils.rs
src/function/src/aws/nexmark/window.rs
src/playground/main.rs
src/runtime/Cargo.toml
src/runtime/src/config.rs
src/runtime/src/config/flock.toml
src/runtime/src/context.rs
src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/executor/mod.rs
src/runtime/src/prelude.rs
src/runtime/src/transform.rs
src/test/src/lib.rs
src/test/src/nexmark.rs

feat!: split epoch to support 1M-10M events/sec from data source

---

src/function/src/aws/nexmark/window.rs

fix: update epoch's uuid  for the next window

---

src/function/src/aws/nexmark/executor.rs
src/function/src/aws/nexmark/utils.rs
src/function/src/aws/nexmark/window.rs

This is a follow-up work of #345
Closes #.

feat: split epoch for window queries

---

bench/Cargo.toml
bench/nexmark/main.rs
nexmark.sh
src/driver/Cargo.toml
src/driver/src/logwatch/mod.rs
src/driver/src/logwatch/tail.rs
src/function/src/aws/nexmark/main.rs
src/runtime/src/context.rs
src/runtime/src/payload.rs

feat: add flock watchlog tail

---

bench/nexmark/main.rs
src/driver/src/deploy/lambda.rs
src/driver/src/deploy/mod.rs
src/function/src/aws/nexmark/executor.rs
src/function/src/aws/nexmark/main.rs
src/function/src/aws/nexmark/utils.rs
src/function/src/aws/nexmark/window.rs
src/runtime/src/context.rs

fix: refine log info in lambda

---

src/runtime/src/datasource/ysb/event.rs
src/runtime/src/datasource/ysb/generator.rs
src/runtime/src/datasource/ysb/mod.rs
src/runtime/src/datasource/ysb/query.rs
src/runtime/src/datasource/ysb/ysb.rs

feat: add local test for ysb query

---

bench/nexmark/main.rs
flock.toml
src/bin/cli/Cargo.toml
src/bin/cli/src/s3.rs
src/driver/src/deploy/lambda.rs
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/main.rs
src/runtime/Cargo.toml
src/runtime/src/context.rs
src/runtime/src/datasource/ysb/query.rs
src/runtime/src/datasource/ysb/ysb.rs
src/runtime/src/encoding.rs
src/runtime/src/payload.rs
src/runtime/src/transform.rs
src/test/src/lib.rs

fix: add q4's plan to s3 and enable zstd

---

flock.toml
src/function/src/aws/nexmark/utils.rs

fix: tuning the payload size for different queries

---

README.md
bench/nexmark/main.rs
flock.toml
nexmark.sh
src/bin/cli/src/repl.rs
src/driver/src/deploy/lambda.rs
src/function/src/aws/lambda.rs
src/function/src/aws/nexmark/actor.rs
src/function/src/aws/nexmark/main.rs
src/function/src/aws/nexmark/utils.rs
src/playground/main.rs
src/test/src/lib.rs

fix: refine config parameters

---

README.md
bench/Cargo.toml
bench/nexmark/main.rs
src/driver/Cargo.toml
src/driver/src/deploy/common.rs
src/driver/src/deploy/flock.rs
src/driver/src/deploy/mod.rs
src/playground/main.rs

fix: move common functions to deploy module

---

README.md
bench/Cargo.toml
bench/nexmark/main.rs
bench/ysb/main.rs
flock_bench.sh
rustfmt.toml
src/bin/cli/Cargo.toml
src/driver/Cargo.toml
src/driver/src/deploy/flock.rs
src/driver/src/funcgen/function.rs
src/function/Cargo.toml
src/function/src/aws/actor.rs
src/function/src/aws/deprecated/lambda.rs
src/function/src/aws/main.rs
src/function/src/aws/window.rs
src/playground/Cargo.toml
src/runtime/Cargo.toml
src/runtime/src/context.rs
src/runtime/src/datasink/mod.rs
src/runtime/src/error.rs
src/runtime/src/executor/mod.rs
src/runtime/src/lib.rs
src/runtime/src/payload.rs
src/runtime/src/prelude.rs
src/runtime/src/transform.rs
src/test/Cargo.toml

feat!: support data sink to aws sqs and s3

---

src/function/src/aws/window.rs
src/runtime/src/datasource/mod.rs
src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/datasource/ysb/ysb.rs
src/runtime/src/payload.rs

optimize: concurrent async invocations

---

bench/nexmark/main.rs
bench/ysb/main.rs
src/driver/src/deploy/common.rs

optimize: bigger memory (more vcpu) for data generator function

---

.gitignore
Cargo.toml
scripts/parser/cloudwatch/Cargo.toml
scripts/parser/cloudwatch/src/main.rs

feat: add script to parse log and report result

---

src/function/src/aws/actor.rs
src/function/src/aws/window.rs

fix: don't sink if output is empty

---

bench/nexmark/main.rs
bench/ysb/main.rs
flock.toml
flock_bench.sh
src/driver/src/deploy/common.rs
src/function/src/aws/actor.rs
src/function/src/aws/deprecated/lambda.rs
src/function/src/aws/main.rs
src/function/src/aws/window.rs
src/runtime/src/arena/mod.rs
src/runtime/src/datasource/mod.rs
src/runtime/src/datasource/nexmark/nexmark.rs
src/runtime/src/datasource/ysb/ysb.rs
src/runtime/src/transform.rs

feat: support sync function invocation option

---

bench/Cargo.toml
bench/nexmark/main.rs
bench/s3/main.rs
src/driver/src/deploy/common.rs
src/function/Cargo.toml
src/function/src/aws/actor.rs
src/function/src/aws/main.rs
src/function/src/aws/s3/mod.rs
src/function/src/aws/s3/source.rs
src/runtime/src/datasource/mod.rs

baseline: use S3 as function comm. medium

---

bench/nexmark/main.rs
bench/ysb/main.rs
flock.toml
flock_bench.sh
src/driver/src/deploy/common.rs
src/function/src/aws/actor.rs

add memory size option in the script
Closes #371 

feat: support error retries and exponential backoff

---

flock_bench.sh
src/driver/src/deploy/common.rs
src/function/src/aws/actor.rs
src/runtime/src/arena/mod.rs
src/runtime/src/error.rs

feat: enable mimalloc to improve the peformance

---

scripts/parser/cloudwatch/src/main.rs
src/function/src/aws/actor.rs

fix: optimize empty data sink (skip serde)

---

bench/nexmark/main.rs
bench/ysb/main.rs
src/driver/src/funcgen/function.rs
src/function/src/aws/actor.rs
src/function/src/aws/deprecated/lambda.rs
src/function/src/aws/s3/source.rs
src/runtime/src/context.rs
src/runtime/src/datasink/mod.rs
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q10.rs
src/runtime/src/datasource/nexmark/queries/q10.sql
src/runtime/src/executor/mod.rs
src/runtime/src/payload.rs
src/runtime/src/query/stream.rs
src/runtime/src/transform.rs

feat: add q10 in local test

---

src/runtime/Cargo.toml
src/runtime/src/datasource/nexmark/queries/mod.rs
src/runtime/src/datasource/nexmark/queries/q11.rs
src/runtime/src/datasource/nexmark/queries/q11.sql
src/runtime/src/payload.rs

feat!: support nexmark q11 in local

---

.codecov.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/push.yml
.github/workflows/rust.yml
.pre-commit-config.yaml
README.md
docs/css/extra.css
docs/css/fancyverb.css
docs/js/accessibility.js
src/playground/README.md

docs: add precommit `prettier` for markdown

---

flock/src/datasource/epoch.rs
flock/src/datasource/mod.rs
flock/src/datasource/nexmark/event.rs
flock/src/datasource/nexmark/generator.rs
flock/src/datasource/nexmark/nexmark.rs
flock/src/datasource/nexmark/queries/q0.rs
flock/src/datasource/nexmark/queries/q1.rs
flock/src/datasource/nexmark/queries/q10.rs
flock/src/datasource/nexmark/queries/q11.rs
flock/src/datasource/nexmark/queries/q13.rs
flock/src/datasource/nexmark/queries/q2.rs
flock/src/datasource/nexmark/queries/q3.rs
flock/src/datasource/nexmark/queries/q4.rs
flock/src/datasource/nexmark/queries/q5.rs
flock/src/datasource/nexmark/queries/q6.rs
flock/src/datasource/nexmark/queries/q6_v2.rs
flock/src/datasource/nexmark/queries/q6_v3.rs
flock/src/datasource/nexmark/queries/q7.rs
flock/src/datasource/nexmark/queries/q8.rs
flock/src/datasource/nexmark/queries/q9.rs
flock/src/datasource/ysb/event.rs
flock/src/datasource/ysb/generator.rs
flock/src/datasource/ysb/query.rs
flock/src/datasource/ysb/ysb.rs

to avoid the conflict with chrono::DateTime

fix: rename datetime to epoch

---

.github/workflows/rust.yml
benchmarks/nexmark/main.rs
benchmarks/ysb/main.rs
flock/src/datasink/mod.rs
flock/src/datasource/nexmark/nexmark.rs
flock/src/datasource/nexmark/queries/q0.rs
flock/src/datasource/nexmark/queries/q1.rs
flock/src/datasource/nexmark/queries/q10.rs
flock/src/datasource/nexmark/queries/q11.rs
flock/src/datasource/nexmark/queries/q13.rs
flock/src/datasource/nexmark/queries/q2.rs
flock/src/datasource/nexmark/queries/q3.rs
flock/src/datasource/nexmark/queries/q4.rs
flock/src/datasource/nexmark/queries/q5.rs
flock/src/datasource/nexmark/queries/q6.rs
flock/src/datasource/nexmark/queries/q6_v2.rs
flock/src/datasource/nexmark/queries/q6_v3.rs
flock/src/datasource/nexmark/queries/q7.rs
flock/src/datasource/nexmark/queries/q8.rs
flock/src/datasource/nexmark/queries/q9.rs
flock/src/datasource/ysb/query.rs
flock/src/datasource/ysb/ysb.rs
flock/src/lib.rs
flock/src/prelude.rs
flock/src/runtime/arena/mod.rs
flock/src/runtime/executor/mod.rs
flock/src/runtime/mod.rs
flock/src/runtime/payload.rs
flock/src/tests/nexmark.rs
flock/src/transmute.rs

fix: rename transform to transmute

---

README.md

doc: add links for each query in readme

---

.github/workflows/rust.yml
.pre-commit-config.yaml
benchmarks/Cargo.toml
flock/Cargo.toml
flock/src/datasource/nexmark/queries/q11.rs
playground/Cargo.toml
scripts/parser/cloudwatch/Cargo.toml

fix: using dataframe api for query 11

---

README.md
flock/src/datasource/nexmark/queries/q11.rs

fix: add session window after interval timeout

---

benchmarks/nexmark/main.rs
benchmarks/nexmark/query/q10.sql
benchmarks/s3/main.rs
benchmarks/ysb/main.rs
flock-function/src/aws/actor.rs
flock/Cargo.toml
flock/src/config.toml
flock/src/datasink/mod.rs
flock/src/driver/deploy/common.rs
flock/src/driver/deploy/mod.rs
flock/src/error.rs
flock/src/lib.rs
flock/src/prelude.rs
flock/src/services.rs
flock_bench.sh

feat!: add sink type: efs

---

benchmarks/nexmark/main.rs
flock/src/datasource/nexmark/nexmark.rs
flock_bench.sh

feat!: nexmark q10 on cloud functions

---

benchmarks/nexmark/main.rs
benchmarks/nexmark/query/q11.sql
flock-function/Cargo.toml
flock-function/src/aws/actor.rs
flock-function/src/aws/main.rs
flock-function/src/aws/nexmark/source.rs
flock-function/src/aws/window.rs
flock/src/datasource/nexmark/config.rs
flock/src/datasource/nexmark/mod.rs
flock/src/datasource/nexmark/nexmark.rs
flock/src/driver/deploy/config.rs
flock/src/transmute.rs
flock_bench.sh

fix: add nexmark q11 on cloud functions

---

flock-function/Cargo.toml
flock-function/src/aws/actor.rs
flock-function/src/aws/window.rs
flock/src/config.toml
flock/src/runtime/arena/mod.rs
flock/src/runtime/payload.rs

This PR can address the session window issue.
Closes #394 

fix: add `rand u128` to payload's `tid`

---

flock-cli/Cargo.toml
flock-cli/src/lambda.rs
flock-cli/src/main.rs
flock-cli/src/repl.rs

feat!: add list and delete functions in flock-cli

---

benchmarks/src/lib.rs
benchmarks/src/nexmark/main.rs
benchmarks/src/ysb/main.rs
flock-cli/src/main.rs
flock-cli/src/repl.rs
flock-cli/src/ysb.rs
flock/src/driver/deploy/config.rs
flock/src/driver/deploy/mod.rs
flock/src/services.rs

feat: add ysb bench in flock-cli

---

benchmarks/src/lib.rs
benchmarks/src/nexmark/main.rs
benchmarks/src/rainbow.rs
flock-cli/src/args.rs
flock-cli/src/fsql.rs
flock-cli/src/lambda.rs
flock-cli/src/main.rs
flock-cli/src/nexmark.rs
flock-cli/src/s3.rs
flock-cli/src/ysb.rs
flock-function/src/aws/window.rs

fix: refine benchmark output

---

flock-cli/Cargo.toml
flock-cli/src/args.rs
flock-cli/src/fsql.rs
flock-cli/src/lambda.rs
flock-cli/src/nexmark.rs
flock-cli/src/repl.rs
flock-cli/src/s3.rs
flock-cli/src/ysb.rs
scripts/parser/cloudwatch/Cargo.toml

fix: update clap requirement from 2.33.3 to 3.0.0

---

flock_bench.sh

fix: update `flock_bench.sh` since we have `flock-cli` now

---

benchmarks/Cargo.toml
benchmarks/src/nexmark/main.rs
benchmarks/src/nexmark/query/q13.sql
benchmarks/src/s3/main.rs
flock-cli/src/nexmark.rs
flock-function/Cargo.toml
flock-function/src/aws/actor.rs
flock-function/src/aws/window.rs
flock/Cargo.toml
flock/src/config.toml
flock/src/datasource/nexmark/event.rs
flock/src/datasource/nexmark/nexmark.rs
flock/src/datasource/nexmark/queries/q13.sql
flock/src/services.rs
flock_bench.sh

feat: support nexmark q13 on cloud functions

---

flock/Cargo.toml
flock/src/runtime/arena/mod.rs

feat: repalce std hashmap with Google's SwissTable hash map impl

---

.pre-commit-config.yaml
README.md
benchmarks/Cargo.toml
benchmarks/src/nexmark/main.rs
benchmarks/src/ysb/main.rs
flock-cli/Cargo.toml
flock-cli/src/nexmark.rs
flock-cli/src/ysb.rs
flock-function/Cargo.toml
flock/Cargo.toml
flock/src/configs/aws_lambda.rs
flock/src/driver/deploy/mod.rs
flock/src/services.rs
flock_bench.sh
playground/Cargo.toml
scripts/build_arm64.sh

feat: enable ARM-based Lambda

---

benchmarks/src/nexmark/main.rs
benchmarks/src/s3/main.rs
flock/Cargo.toml
flock/src/aws/efs.rs
flock/src/datasource/nexmark/event.rs
flock/src/datasource/nexmark/mod.rs
flock/src/distributed_plan/memory_stream.rs
flock/src/distributed_plan/mod.rs
flock/src/distributed_plan/nexmark/q1.dag
flock/src/distributed_plan/nexmark/q10.dag
flock/src/distributed_plan/nexmark/q11.dag
flock/src/distributed_plan/nexmark/q12.dag
flock/src/distributed_plan/nexmark/q13.dag
flock/src/distributed_plan/nexmark/q2.dag
flock/src/distributed_plan/nexmark/q3.dag
flock/src/distributed_plan/nexmark/q5.dag
flock/src/distributed_plan/nexmark/q6.dag
flock/src/distributed_plan/nexmark/q7.dag
flock/src/distributed_plan/nexmark/q8.dag
flock/src/distributed_plan/nexmark/q9.dag
flock/src/distributed_plan/planner.rs
flock/src/distributed_plan/shuffle_writer.rs
flock/src/lib.rs
flock/src/runtime/context.rs

refactor!: add distributed_plan module

---

benchmarks/src/ysb/main.rs
flock/src/datasource/ysb/mod.rs
flock/src/distributed_plan/planner.rs
flock/src/distributed_plan/ysb/ysb.dag

feat: add ysb query's distributed plan

---

benchmarks/Cargo.toml
flock-cli/Cargo.toml
flock-function/Cargo.toml
flock-function/src/aws/mod.rs
flock-function/src/azure/mod.rs
flock-function/src/gcp/mod.rs
flock-function/src/launcher.rs
flock-function/src/lib.rs
flock/Cargo.toml
playground/Cargo.toml

refactor!: add launcher for different function services

---

flock-function/Cargo.toml
flock-function/src/aws/mod.rs
flock-function/src/azure/mod.rs
flock-function/src/gcp/mod.rs
flock-function/src/launcher.rs
flock-function/src/lib.rs
flock-function/src/local.rs
flock/src/datasource/mod.rs
flock/src/prelude.rs
flock/src/query.rs

feat!: add local launcher interface

---

.github/workflows/rust.yml
.github/workflows/scheduled-build.yml
benchmarks/Cargo.toml
flock-function/Cargo.toml
flock-function/src/aws/cloud_context.rs
flock-function/src/aws/main.rs
flock/Cargo.toml

ci: add arm targets

---

.cargo/config
.github/workflows/rust.yml
.github/workflows/scheduled-build.yml
flock-function/src/aws/main.rs
header

ci: update cron job

---

.github/workflows/scheduled-build.yml
scripts/rainbow.sh

fix: aarch64-linux-gnu-strip  remove symbols

---

.github/workflows/rust.yml
flock-function/src/aws/main.rs
flock/src/launcher/aws/mod.rs
flock/src/launcher/mod.rs
flock/src/runtime/context.rs

test: compare local and dist query result

---

playground/README.md

fix: invalid image links

---

flock-function/src/aws/nexmark/source.rs
flock-function/src/aws/s3/source.rs
flock-function/src/aws/window.rs
flock/src/datasource/mod.rs
flock/src/datasource/nexmark/nexmark.rs
flock/src/datasource/ysb/ysb.rs

feat: distributed flock functions for nexmark

---

.github/workflows/rust.yml
.github/workflows/scheduled-build.yml
flock-function/src/aws/actor.rs
flock-function/src/aws/window.rs
flock/src/runtime/payload.rs

feat: distributed dataflow pipeline

---

benchmarks/src/nexmark/distributed.rs
benchmarks/src/nexmark/main.rs
benchmarks/src/ysb/main.rs
flock-cli/src/nexmark.rs
flock-function/src/aws/actor.rs
flock-function/src/aws/cloud_context.rs
flock-function/src/aws/window.rs
flock/src/aws/s3.rs
flock/src/launcher/aws/mod.rs
flock/src/launcher/azure/mod.rs
flock/src/launcher/gcp/mod.rs
flock/src/launcher/local.rs
flock/src/launcher/mod.rs
flock/src/lib.rs
flock/src/prelude.rs
flock/src/query.rs
flock/src/runtime/arena/mod.rs
flock/src/runtime/context.rs
flock/src/state/efs.rs
flock/src/state/mod.rs
flock/src/state/s3.rs

feat: add state module to manage the query states

---

flock-function/src/aws/actor.rs
flock/src/launcher/aws/mod.rs

test: nexmark q4 and ysb in distributed mode

---

flock/src/launcher/aws/mod.rs
flock/src/runtime/context.rs

test: dist hash join with sort

---

configure
flock-cli/Cargo.toml
flock-cli/src/repl.rs
flock-cli/src/s3.rs
flock/src/aws/s3.rs

feat(cli): add s3 list and delete

---

CITATION.cff
CODE_OF_CONDUCT.md

doc: add code of conduct

---

CODE_OF_CONDUCT.md
README.md
flock-function/src/aws/actor.rs
flock-function/src/aws/window.rs
flock/src/aws/s3.rs
flock/src/configs/flock.toml
flock/src/datasink/mod.rs
flock/src/prelude.rs
flock/src/runtime/arena/mod.rs
flock/src/runtime/payload.rs
flock/src/state/s3.rs

feat(state): optimize s3 state backend

---

playground/Cargo.toml
playground/src/lib.rs
playground/src/payload/mod.rs

feat(playground): test arrow built-in json reader and writer

---

flock-function/src/aws/actor.rs
flock-function/src/aws/nexmark/source.rs
flock/src/runtime/arena/mod.rs

feat(arena): optimize data frame deserialization

---

benchmarks/Cargo.toml
benchmarks/src/arch/main.rs
benchmarks/src/lib.rs
benchmarks/src/nexmark/main.rs
flock-cli/src/arch.rs
flock-cli/src/nexmark.rs
flock-cli/src/repl.rs
flock-function/src/aws/actor.rs
flock-function/src/aws/arch/mod.rs
flock-function/src/aws/arch/ops/filter.sql
flock-function/src/aws/arch/ops/group-by.sql
flock-function/src/aws/arch/ops/join.sql
flock-function/src/aws/arch/ops/sort.sql
flock-function/src/aws/arch/source.rs
flock-function/src/aws/main.rs
flock-function/src/aws/nexmark/source.rs
flock/src/datasource/mod.rs
flock/src/runtime/context.rs

feat(arch): add microbench to evaluate ops on x86_64 and arm64

---

configure

feat(configure): add option to disable handwritten arrow kernels

---

flock/src/datasource/nexmark/nexmark.rs
flock/src/runtime/plan.rs

fix: large plan in s3 as a fallback

---

benchmarks/src/nexmark/main.rs
flock/src/configs/flock.toml

fix(bench): add nexmark q9 plan in s3

---

benchmarks/src/nexmark/main.rs
benchmarks/src/s3/main.rs
flock-function/src/aws/window/session.rs

fix: nexmark queries

---

flock-cli/src/nexmark.rs
flock-function/src/aws/actor.rs
flock/src/datasource/nexmark/nexmark.rs
flock/src/runtime/arena/mod.rs
flock/src/runtime/context.rs
scripts/cloudwatch_log.sh

fix(payload): keep schema in payload  if data is empty

---

benchmarks/src/ysb/centralized.rs
benchmarks/src/ysb/distributed.rs
benchmarks/src/ysb/main.rs
flock-cli/src/ysb.rs
flock-function/src/aws/nexmark/source.rs
flock-function/src/aws/window/mod.rs
flock-function/src/aws/window/tumbling.rs
flock-function/src/aws/ysb/source.rs
flock/src/datasource/ysb/mod.rs

feat(ysb): dist ysb benchmark
